services:
  - type: web
    name: ai-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SPOTIPY_CLIENT_ID
        sync: false
      - key: SPOTIPY_CLIENT_SECRET
        sync: false
      - key: SPOTIPY_REDIRECT_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false 